[package]
name = "cell-gc"
description = "A fun garbage collector for that virtual machine you're writing in Rust"
repository = "https://github.com/jorendorff/cell-gc/"
license = "MIT"
version = "0.1.3"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]

[dependencies]
bit-vec = "0.4"

[dev-dependencies]
compiletest_rs = "0.0"
