[package]
name = "cell-gc-derive"
version = "0.1.0"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]

[lib]
proc_macro = true

[dependencies]
syn = { version = "0.11.4", features = ["aster", "visit"] }
quote = "0.3.12"
