[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "lisp"
version = "0.1.0"

[dependencies]
asexp = "0.3.1"

[dependencies.cell-gc]
path = ".."

[dependencies.cell-gc-derive]
path = "../cell-gc-derive"
