[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "lisp"
version = "0.1.0"

[dependencies]
nom = { git = "https://github.com/Geal/nom", branch = "master" }

[dependencies.cell-gc]
path = ".."

[dependencies.cell-gc-derive]
path = "../cell-gc-derive"
